export const conversionFormulas = [
  {
    id: 'length-meters-feet',
    slug: 'convert-meters-to-feet',
    category: 'Length',
    title: 'Meters to feet',
    formula: 'feet = meters × 3.28084',
    keywords: ['meters to feet', 'm to ft', 'length'],
    example: '10 meters × 3.28084 = 32.8084 feet',
    note: 'Commonly used in construction and height measurements.',
  },
  {
    id: 'length-feet-meters',
    slug: 'convert-feet-to-meters',
    category: 'Length',
    title: 'feet to meters',
    formula: 'meters = feet ÷ 3.28084',
    keywords: ['feet to meters', 'ft to m', 'length'],
    example: '20 feet ÷ 3.28084 = 6.096 meters',
    note: 'Useful when converting US building specs to metric.',
  },
  {
    id: 'length-km-miles',
    slug: 'convert-kilometers-to-miles',
    category: 'Length',
    title: 'kilometers to miles',
    formula: 'miles = kilometers × 0.621371',
    keywords: ['km to miles', 'kilometers to miles'],
    example: '5 kilometers × 0.621371 = 3.106855 miles',
    note: 'Great for converting driving distances.',
  },
  {
    id: 'length-miles-km',
    slug: 'convert-miles-to-kilometers',
    category: 'Length',
    title: 'miles to kilometers',
    formula: 'kilometers = miles ÷ 0.621371',
    keywords: ['miles to km', 'miles to kilometers'],
    example: '10 miles ÷ 0.621371 = 16.0934 kilometers',
    note: 'Used in travel and fitness tracking.',
  },
  {
    id: 'temp-celsius-fahrenheit',
    slug: 'convert-celsius-to-fahrenheit',
    category: 'Temperature',
    title: 'Celsius to Fahrenheit',
    formula: 'F = (C × 9/5) + 32',
    keywords: ['c to f', 'celsius to fahrenheit', 'temperature'],
    example: '0°C × 9/5 + 32 = 32°F',
    note: 'Common for checking weather temperatures.',
  },
  {
    id: 'temp-fahrenheit-celsius',
    slug: 'convert-fahrenheit-to-celsius',
    category: 'Temperature',
    title: 'Fahrenheit to Celsius',
    formula: 'C = (F - 32) × 5/9',
    keywords: ['f to c', 'fahrenheit to celsius', 'temperature'],
    example: '(98°F - 32) × 5/9 = 36.67°C',
    note: 'Helpful for medical or culinary temperature conversions.',
  },
  {
    id: 'weight-kg-lbs',
    slug: 'convert-kilograms-to-pounds',
    category: 'Weight',
    title: 'kilograms to pounds',
    formula: 'lbs = kg × 2.20462',
    keywords: ['kg to lbs', 'kilograms to pounds', 'weight'],
    example: '50 kg × 2.20462 = 110.231 lbs',
    note: 'Used for weight conversion in health and fitness.',
  },
  {
    id: 'weight-lbs-kg',
    slug: 'convert-pounds-to-kilograms',
    category: 'Weight',
    title: 'pounds to kilograms',
    formula: 'kg = lbs ÷ 2.20462',
    keywords: ['lbs to kg', 'pounds to kilograms'],
    example: '100 lbs ÷ 2.20462 = 45.3592 kg',
    note: 'Useful when comparing US and international weight limits.',
  },
  {
    id: 'volume-liters-gallons',
    slug: 'convert-liters-to-gallons',
    category: 'Volume',
    title: 'liters to gallons',
    formula: 'gallons = liters × 0.264172',
    keywords: ['liters to gallons', 'volume'],
    example: '10 liters × 0.264172 = 2.64172 gallons',
    note: 'Useful for converting fuel or liquid measurements.',
  },
  {
    id: 'volume-gallons-liters',
    slug: 'convert-gallons-to-liters',
    category: 'Volume',
    title: 'gallons to liters',
    formula: 'liters = gallons ÷ 0.264172',
    keywords: ['gallons to liters', 'volume'],
    example: '5 gallons ÷ 0.264172 = 18.9271 liters',
    note: 'Helpful for comparing fuel efficiency.',
  },
  {
    id: 'area-sqmeters-sqfeet',
    slug: 'convert-square-meters-to-square-feet',
    category: 'Area',
    title: 'Square meters to square feet',
    formula: 'sq ft = sq m × 10.7639',
    keywords: ['square meters to feet', 'sq m to sq ft', 'area'],
    example: '50 sq m × 10.7639 = 538.195 sq ft',
    note: 'Used for floor plans and property listings.',
  },
  {
    id: 'area-sqfeet-sqmeters',
    slug: 'convert-square-feet-to-square-meters',
    category: 'Area',
    title: 'Square feet to square meters',
    formula: 'sq m = sq ft ÷ 10.7639',
    keywords: ['sq ft to sq m', 'square feet to meters'],
    example: '1000 sq ft ÷ 10.7639 = 92.903 sq m',
    note: 'Helpful for international real estate listings.',
  },
  {
    id: 'speed-kph-mph',
    slug: 'convert-kph-to-mph',
    category: 'Speed',
    title: 'Kilometers per hour to miles per hour',
    formula: 'mph = kph × 0.621371',
    keywords: ['kph to mph', 'speed conversion'],
    example: '100 kph × 0.621371 = 62.1371 mph',
    note: 'Common in vehicle speed conversions.',
  },
  {
    id: 'speed-mph-kph',
    slug: 'convert-mph-to-kph',
    category: 'Speed',
    title: 'Miles per hour to kilometers per hour',
    formula: 'kph = mph ÷ 0.621371',
    keywords: ['mph to kph', 'speed conversion'],
    example: '60 mph ÷ 0.621371 = 96.5606 kph',
    note: 'Useful for driving abroad with different speed units.',
  },
  {
    id: 'time-hours-minutes',
    slug: 'convert-hours-to-minutes',
    category: 'Time',
    title: 'Hours to minutes',
    formula: 'minutes = hours × 60',
    keywords: ['hours to minutes', 'time conversion'],
    example: '2 hours × 60 = 120 minutes',
    note: 'Used for scheduling and time tracking.',
  },
  {
    id: 'time-minutes-hours',
    slug: 'convert-minutes-to-hours',
    category: 'Time',
    title: 'Minutes to hours',
    formula: 'hours = minutes ÷ 60',
    keywords: ['minutes to hours', 'time conversion'],
    example: '180 minutes ÷ 60 = 3 hours',
    note: 'Useful in productivity and calendar planning.',
  },
]
